# permissions for end users to view azureredisinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azureredisinstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-manager
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: azureredisinstance-viewer-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - azureredisinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - azureredisinstances/status
  verbs:
  - get
